import Vue from 'vue';
import {Message, Radio, Row, Col, Menu, Submenu, Tooltip, MenuItem, MenuItemGroup, Container, Header, Aside, Main, Footer, Breadcrumb, BreadcrumbItem, Form, FormItem, Input, InputNumber, Select, Option, OptionGroup, Checkbox, CheckboxButton, CheckboxGroup, DatePicker, TimePicker, RadioGroup, Button, ButtonGroup, Pagination, MessageBox, Tree, Upload, Dialog, Table, TableColumn, Tag, Cascader, Tabs, TabPane, Carousel, CarouselItem, Popover, Step, Steps, Switch, Autocomplete} from 'element-ui';
Vue.component(Message.name, Message);
Vue.component(Radio.name, Radio);
Vue.component(Row.name, Row);
Vue.component(Col.name, Col);
Vue.component(Menu.name, Menu);
Vue.component(Submenu.name, Submenu);
Vue.component(MenuItem.name, MenuItem);
Vue.component(MenuItemGroup.name, MenuItemGroup);
Vue.component(Container.name, Container);
Vue.component(Header.name, Header);
Vue.component(Aside.name, Aside);
Vue.component(Main.name, Main);
Vue.component(Footer.name, Footer);
Vue.component(Breadcrumb.name, Breadcrumb);
Vue.component(BreadcrumbItem.name, BreadcrumbItem);
Vue.component(Form.name, Form);
Vue.component(FormItem.name, FormItem);
Vue.component(Input.name, Input);
Vue.component(InputNumber.name, InputNumber);
Vue.component(Select.name, Select);
Vue.component(Carousel.name, Carousel);
Vue.component(CarouselItem.name, CarouselItem);
Vue.component(Option.name, Option);
Vue.component(OptionGroup.name, OptionGroup);
Vue.component(Checkbox.name, Checkbox);
Vue.component(CheckboxButton.name, CheckboxButton);
Vue.component(CheckboxGroup.name, CheckboxGroup);
Vue.component(DatePicker.name, DatePicker);
Vue.component(TimePicker.name, TimePicker);
Vue.component(RadioGroup.name, RadioGroup);
Vue.component(Button.name, Button);
Vue.component(ButtonGroup.name, ButtonGroup);
Vue.component(Pagination.name, Pagination);
Vue.component(MessageBox.name, MessageBox);
Vue.component(Tree.name, Tree);
Vue.component(Pagination.name, Pagination);
Vue.component(Upload.name, Upload);
Vue.component(Dialog.name, Dialog);
Vue.component(Table.name, Table);
Vue.component(TableColumn.name, TableColumn);
Vue.component(Tag.name, Tag);
Vue.component(Cascader.name, Cascader);
Vue.component(Tooltip.name, Tooltip);
Vue.component(Tabs.name, Tabs);
Vue.component(TabPane.name, TabPane);
Vue.component(Step.name, Step);
Vue.component(Steps.name, Steps);
Vue.component(Switch.name, Switch);
Vue.component(Autocomplete.name, Autocomplete);
Vue.use(Popover);
Vue.prototype.$message = Message;
Vue.prototype.$radio = Radio;
Vue.prototype.$row = Row;
Vue.prototype.$col = Col;
Vue.prototype.$menu = Menu;
Vue.prototype.$submenu = Submenu;
Vue.prototype.$menuitem = MenuItem;
Vue.prototype.$menuitemgroup = MenuItemGroup;
Vue.prototype.$container = Container;
Vue.prototype.$header = Header;
Vue.prototype.$aside = Aside;
Vue.prototype.$main = Main;
Vue.prototype.$footer = Footer;
Vue.prototype.$breadcrumb = Breadcrumb;
Vue.prototype.$breadcrumbItem = BreadcrumbItem;
Vue.prototype.$form = Form;
Vue.prototype.$formItem = FormItem;
Vue.prototype.$input = Input;
Vue.prototype.$inputnumber = InputNumber;
Vue.prototype.$select = Select;
Vue.prototype.$option = Option;
Vue.prototype.$optiongroup = OptionGroup;
Vue.prototype.$checkbox = Checkbox;
Vue.prototype.$checkboxbutton = CheckboxButton;
Vue.prototype.$checkboxgroup = CheckboxGroup;
Vue.prototype.$datepicker = DatePicker;
Vue.prototype.$timepicker = TimePicker;
Vue.prototype.$radiogroup = RadioGroup;
Vue.prototype.$button = Button;
Vue.prototype.$buttongroup = ButtonGroup;
Vue.prototype.$pagination = Pagination;
Vue.prototype.$messagebox = MessageBox;
Vue.prototype.$confirm = MessageBox.confirm;
Vue.prototype.$tree = Tree;
Vue.prototype.$alert = MessageBox.alert;
Vue.prototype.$upload = Upload;
Vue.prototype.$table = Table;
Vue.prototype.$tablecolumn = TableColumn;
Vue.prototype.$tag = Tag;
Vue.prototype.$tabs = Tabs;
Vue.prototype.tabpane = TabPane;
Vue.prototype.$tooltip = Tooltip;
Vue.prototype.$step = Step;
Vue.prototype.$steps = Steps;
Vue.prototype.$switch = Switch;
Vue.prototype.$autocomplete = Autocomplete;
export default {
};
